-- T26_ITEM_GROUP_BACKUP

CREATE TABLE IF NOT EXISTS T26_ITEM_GROUP_BACKUP (
	C26_ITEM_GROUP_ID INT NOT NULL,
    C26_ITEM_GROUP_NAME VARCHAR(255) NOT NULL,
    C26_STATUS BIT(1) DEFAULT(1) NOT NULL,
    C26_COPIED_AT DATETIME DEFAULT(current_timestamp())
);

ALTER TABLE T01_ITEM
DROP FOREIGN KEY FK_T01_T07;

ALTER TABLE T01_ITEM
ADD CONSTRAINT FK_T01_T07 FOREIGN KEY (C01_ITEM_GROUP_ID) REFERENCES T07_ITEM_GROUP(C07_ITEM_GROUP_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

select * from t03_item_detail;

-- Xử lý vẫn đề của ItemDetail và OrderDetail
ALTER TABLE t03_item_detail DROP FOREIGN KEY FK_T03_T01; 
ALTER TABLE t03_item_detail DROP FOREIGN KEY FK_T03_T02; ALTER TABLE t03_item_detail DROP INDEX FK_T03_T02;
ALTER TABLE t03_item_detail DROP COLUMN C03_ITEM_DETAIL_ID;

ALTER TABLE t03_item_detail DROP PRIMARY KEY;
ALTER TABLE t03_item_detail ADD C03_ITEM_DETAIL_ID INT PRIMARY KEY auto_increment FIRST;
ALTER TABLE t03_item_detail ADD CONSTRAINT UNQ_ITEM_SIZE UNIQUE (C03_ITEM_ID, C03_SIZE_ID);

ALTER TABLE t03_item_detail ADD CONSTRAINT FK_T03_T02 FOREIGN KEY (C03_SIZE_ID) REFERENCES t02_size(C02_SIZE_ID);
ALTER TABLE t03_item_detail ADD CONSTRAINT FK_T03_T01 FOREIGN KEY (C03_ITEM_ID) REFERENCES t01_item(C01_ITEM_ID);


ALTER TABLE t12_order_detail DROP FOREIGN KEY FK_T12_T01; 
ALTER TABLE t12_order_detail DROP FOREIGN KEY FK_T12_T09; ALTER TABLE t12_order_detail DROP INDEX FK_T12_T01;


ALTER TABLE t12_order_detail DROP primary key;
ALTER TABLE t12_order_detail DROP column C12_ITEM_ID;
ALTER TABLE t12_order_detail ADD C12_ITEM_DETAIL_ID INT NOT NULL AFTER C12_ORDER_ID;

ALTER TABLE t12_order_detail ADD PRIMARY KEY (C12_ORDER_ID, C12_ITEM_DETAIL_ID);

ALTER TABLE t12_order_detail ADD CONSTRAINT FK_T12_T03 FOREIGN KEY (C12_ITEM_DETAIL_ID) REFERENCES t03_item_detail(C03_ITEM_DETAIL_ID);
ALTER TABLE t12_order_detail ADD CONSTRAINT FK_T12_T09 FOREIGN KEY (C12_ORDER_ID) REFERENCES t09_order(C09_ORDER_ID);

-- t14_order_status_detail
ALTER TABLE t14_order_status_detail
DROP PRIMARY KEY,
ADD PRIMARY KEY (C14_ORDER_ID, C14_ORDER_STATUS_ID);


