-- T19_VOUCHER, T09_ORDER, T10_BILL, T12_ORDER_DETAIL

-- T19_VOUCHER
CREATE TABLE IF NOT EXISTS T19_VOUCHER (
	C19_VOUCHER_ID INT PRIMARY KEY AUTO_INCREMENT,
    C19_REDUCING_MONEY FLOAT(10, 2),
    C19_REDUCING_IN_PERCENT INT,
    C19_DATE_START DATE DEFAULT(curdate()),
    C19_DATE_END DATE NOT NULL,
    C19_VOUCHER_STATUS BIT(1) NOT NULL DEFAULT(1)
);

-- T09_ORDER
CREATE TABLE IF NOT EXISTS T09_ORDER (
	C09_ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    C09_ORDER_TIME DATETIME NOT NULL DEFAULT(CURRENT_TIMESTAMP()),
    C09_PAYMENT_METHOD_ID INT NOT NULL,
    C09_CUSTOMER_ID INT NOT NULL,
    C09_DELIVERY_ADDRESS_ID INT NOT NULL,
    C09_EMPLOYEE_ID INT NOT NULL,
    CONSTRAINT FK_T09_T11 FOREIGN KEY (C09_PAYMENT_METHOD_ID) REFERENCES T11_PAYMENT_METHOD(C11_PAYMENT_METHOD_ID),
    CONSTRAINT FK_T09_T15 FOREIGN KEY (C09_CUSTOMER_ID) REFERENCES T15_CUSTOMER(C15_CUSTOMER_ID),
    CONSTRAINT FK_T09_T18 FOREIGN KEY (C09_DELIVERY_ADDRESS_ID) REFERENCES T18_DELIVERY_ADDRESS(C18_DELIVERY_ADDRESS_ID),
    CONSTRAINT FK_T09_T16 FOREIGN KEY (C09_EMPLOYEE_ID) REFERENCES T16_EMPLOYEE(C16_EMPLOYEE_ID)
);

-- T10_BILL
CREATE TABLE IF NOT EXISTS T10_BILL (
	C10_BILL_ID INT PRIMARY KEY AUTO_INCREMENT,
	C10_ORDER_ID INT NOT NULL,
	C10_DELIVERY_FEE INT NOT NULL,
	C10_VOUCHER_ID INT NOT NULL,
	C10_TOTAL_OF_MONEY FLOAT(10, 2) NOT NULL,
    CONSTRAINT FK_T10_T09 FOREIGN KEY (C10_ORDER_ID) REFERENCES T09_ORDER(C09_ORDER_ID),
    CONSTRAINT FK_T10_T19 FOREIGN KEY (C10_VOUCHER_ID) REFERENCES T19_VOUCHER(C19_VOUCHER_ID)
);

-- T12_ORDER_DETAIL
CREATE TABLE IF NOT EXISTS T12_ORDER_DETAIL (
	C12_ORDER_ID INT,
	C12_ITEM_ID INT,
	C12_AMOUNT INT NOT NULL,
	PRIMARY KEY (C12_ORDER_ID, C12_ITEM_ID),
    CONSTRAINT FK_T12_T09 FOREIGN KEY (C12_ORDER_ID) REFERENCES T09_ORDER(C09_ORDER_ID),
    CONSTRAINT FK_T12_T01 FOREIGN KEY (C12_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);
