-- T17_DEPARTMENT, T16_EMPLOYEE
-- T06_PROVIDER, T04_WAREHOUSE_RECEIPT, T05_WAREHOUSE_RECEIPT_DETAIL

-- T17_DEPARTMENT
CREATE TABLE IF NOT EXISTS T17_DEPARTMENT (
	C17_DEPARTMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    C17_DEPARTMENT_NAME TEXT NOT NULL
);

-- T16_EMPLOYEE
CREATE TABLE IF NOT EXISTS T16_EMPLOYEE (
	C16_EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
    C16_EMPLOYEE_NAME VARCHAR(255) NOT NULL,
    C16_EMPLOYEE_EMAIL TEXT NOT NULL,
    C16_EMPLOYEE_ADDRESS TEXT NOT NULL,
    C16_EMPLOYEE_PHONE VARCHAR(20) NOT NULL,
    C16_EMPLOYEE_PASSWORD TEXT NOT NULL,
    C16_GMAIL_TOKEN TEXT NOT NULL,
    C16_DEPARTMENT_ID INT NOT NULL,
    CONSTRAINT FK_T16_T17 FOREIGN KEY (C16_DEPARTMENT_ID) REFERENCES T17_DEPARTMENT(C17_DEPARTMENT_ID)
);

-- T6_PROVIDER
CREATE TABLE IF NOT EXISTS T06_PROVIDER (
	C06_PROVIDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    C06_PROVIDER_NAME VARCHAR(255) NOT NULL,
    C06_PROVIDER_TAX VARCHAR(5) NOT NULL
);

-- T04_WAREHOUSE_RECEIPT
CREATE TABLE IF NOT EXISTS T04_WAREHOUSE_RECEIPT (
	C04_WHRECEIPT_ID INT PRIMARY KEY AUTO_INCREMENT,
    C04_WHRECEIPT_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    C04_EMPLOYEE_ID INT NOT NULL,
    CONSTRAINT FK_T04_T16 FOREIGN KEY (C04_EMPLOYEE_ID) REFERENCES T16_EMPLOYEE(C16_EMPLOYEE_ID)
);

-- T05_WAREHOUSE_RECEIPT_DETAIL
CREATE TABLE IF NOT EXISTS T05_WAREHOUSE_RECEIPT_DETAIL (
	C05_WHRECEIPT_ID INT NOT NULL,
    C05_ITEM_ID INT NOT NULL,
    C05_AMOUNT INT NOT NULL,
    C05_BUY_PRICE FLOAT(10, 2) NOT NULL,
    C05_PROVIDER_ID INT NOT NULL,
    PRIMARY KEY (C05_WHRECEIPT_ID, C05_ITEM_ID),
    CONSTRAINT FK_T05_T04 FOREIGN KEY (C05_WHRECEIPT_ID) REFERENCES T04_WAREHOUSE_RECEIPT(C04_WHRECEIPT_ID),
    CONSTRAINT FK_T05_T01 FOREIGN KEY (C05_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID),
    CONSTRAINT FK_T05_T06 FOREIGN KEY (C05_PROVIDER_ID) REFERENCES T06_PROVIDER(C06_PROVIDER_ID)
);
