CREATE DATABASE lesson18_exam char set utf8mb4;

use lesson18_exam;

DROP TABLE IF EXISTS CLASS;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS RESULT;

-- CLASS;
CREATE TABLE T01_CLASS(
	C01_CLASS_ID INT AUTO_INCREMENT PRIMARY KEY,
    C01_CLASS_NAME VARCHAR(255) NOT NULL,
    C01_TEACHER VARCHAR(255) NOT NULL
);

-- STUDENT;
CREATE TABLE T02_STUDENT (
    C02_STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    C02_NAME VARCHAR(100) NOT NULL,
    C02_GENDER ENUM('Male', 'Female') NOT NULL,
    C02_CLASS_ID INT,
    CONSTRAINT FK_T02_T01 FOREIGN KEY (C02_CLASS_ID) REFERENCES T01_CLASS(C01_CLASS_ID)
);

-- RESULTS
CREATE TABLE T03_RESULT (
    C03_STUDENT_ID INT,
    C03_SUBJECT VARCHAR(100) NOT NULL,
    C03_SCORE DECIMAL(2,1) NOT NULL,
    PRIMARY KEY (C03_STUDENT_ID, C03_SUBJECT),
    CONSTRAINT FK_T03_T02 FOREIGN KEY (C03_STUDENT_ID) REFERENCES T02_STUDENT(C02_STUDENT_ID)
);

-- INSERT

INSERT INTO T01_CLASS (C01_CLASS_NAME, C01_TEACHER)
VALUES ('12A', 'Ho Cong Trung'),
	   ('12B', 'Dang Tu Anh'),
       ('12C', 'Nguyen Van Tam');


INSERT INTO T02_STUDENT (C02_NAME, C02_GENDER, C02_CLASS_ID)
VALUES ('Dinh Thi Ngoc', 'Female', 2),
	   ('Nguyen Thanh Hung', 'Male', 1),
       ('Tran Mai Hoa', 'Female', 2),
       ('Doan Quang Vinh', 'Male', 1),
       ('Cao Anh Dao', 'Female', 3),
       ('Tran Kim Tuyen', 'Male', 3);
      
INSERT INTO T03_RESULT (C03_STUDENT_ID, C03_SUBJECT, C03_SCORE)
VALUES (1, 'Math', 8.0),
	   (2, 'Literature', 7.0),
       (3, 'History', 9.5),
       (4, 'Math', 6.8),
	   (5, 'Literature', 4.9),
       (6, 'History', 8.2);

-- SELECT
SELECT C02_STUDENT_ID, C02_NAME FROM T02_STUDENT ORDER BY C02_STUDENT_ID;
SELECT * FROM T01_CLASS;
SELECT * FROM T02_STUDENT;
SELECT * FROM T03_RESULT;

-- QUESTION
-- 1. WHAT IS PRIMARY KEY OF RESULT TABLE?
-- - COMPOSITE KEY (C03_STUDENT_ID, C03_SUBJECT) 

-- 2. LIST NAME, GENDER AND TEACHER NAME OF ALL STUDENTS

SELECT t02.C02_NAME AS STUDENT_NAME,
	   t02.C02_GENDER AS GEMDER,
       t01.C01_TEACHER AS TEACHER_NAME
  FROM T02_STUDENT t02
  JOIN T01_CLASS t01 ON t02.C02_CLASS_ID = t01.C01_CLASS_ID;
  
-- 3. LIST TEACHER NAME AND NUMBER OF ALL STUDENT IN CLASS 12C

SELECT t01.C01_TEACHER AS TEACHER_NAME,
 COUNT(t02.C02_STUDENT_ID) AS NUMBER_OF_ALL_STUDENT_12C
  FROM T01_CLASS t01
  JOIN T02_STUDENT t02 ON t01.C01_CLASS_ID = t02.C02_CLASS_ID
 WHERE t01.C01_CLASS_NAME = '12C'
 GROUP BY t01.C01_TEACHER;
 
 -- 4. LIST THE CLASS NAME AND NUMBER OF STUDENTS WHO HAVE GOOD AT MATCH(SCORE>=8)
 -- AND GOOD AT LITERATURE(SCORE>=8)
 
 SELECT t01.C01_CLASS_NAME AS CLASS_NAME,
	   t03.C03_SUBJECT AS SUBJECT,
 COUNT(DISTINCT T02.C02_STUDENT_ID) AS NUMBER_OF_EXCELLENT_STUDENTS
  FROM T03_RESULT t03
  JOIN T02_STUDENT t02 ON t03.C03_STUDENT_ID = t02.C02_STUDENT_ID
  JOIN T01_CLASS t01 ON t02.C02_CLASS_ID = t01.C01_CLASS_ID
 WHERE t03.C03_SUBJECT IN ('Math', 'Literature') AND t03.C03_SCORE >= 8
 GROUP BY t01.C01_CLASS_NAME, t03.C03_SUBJECT;
