-- Tạo table liên quan đến loại hàng và mặt hàng 
-- AUTO_INCREMENT khi thêm dữ liệu nếu không khai báo dữ liệu cho column thì lấy giá trị lớn nhất của column đó + 1

-- T07_ITEM_GROUP
-- T01_ITEM
-- T02_SIZE
-- T03_ITEM_DETAIL 
-- T07_ITEM_GROUP
CREATE TABLE IF NOT EXISTS T07_ITEM_GROUP (
	C07_ITEM_GROUP_ID INT PRIMARY KEY AUTO_INCREMENT,
	C07_ITEM_GROUP_NAME VARCHAR(255) UNIQUE NOT NULL,
	C07_STATUS BIT(1) DEFAULT 0
);
ALTER TABLE T07_ITEM_GROUP CHANGE C07_STATUS C07_STATUS BIT(1) NOT NULL DEFAULT 0;

-- T01_ITEM
CREATE TABLE IF NOT EXISTS T01_ITEM (
	C01_ITEM_ID INT AUTO_INCREMENT,
    C01_ITEM_NAME VARCHAR(255) NOT NULL,
    C01_ITEM_GROUP_ID INT NOT NULL,
    C01_COLOR VARCHAR(50) NOT NULL,
    PRIMARY KEY (C01_ITEM_ID),
    CONSTRAINT FK_T01_T07 FOREIGN KEY (C01_ITEM_GROUP_ID) REFERENCES T07_ITEM_GROUP(C07_ITEM_GROUP_ID)
);

-- T02_SIZE
CREATE TABLE IF NOT EXISTS T02_SIZE (
	C02_SIZE_ID INT AUTO_INCREMENT PRIMARY KEY,
    C02_SIZE_NAME VARCHAR(10) NOT NULL,
    C02_GENDER BIT(1) NOT NULL,
    C02_SIZE_DESC TEXT NOT NULL,
    CONSTRAINT CHK_SIZE_NAME CHECK (C02_SIZE_NAME IN ('S', 'M', 'XL', '2XL'))
);

-- T03_ITEM_DETAIL 
CREATE TABLE IF NOT EXISTS T03_ITEM_DETAIL (
	C03_ITEM_ID INT NOT NULL,
	C03_SIZE_ID INT NOT NULL,
	C03_SALES_PRICE FLOAT(10,2) NOT NULL,
	C03_AMOUNT INT NOT NULL,
    PRIMARY KEY (C03_ITEM_ID, C03_SIZE_ID),
    CONSTRAINT FK_T03_T01 FOREIGN KEY (C03_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID),
    CONSTRAINT FK_T03_T02 FOREIGN KEY (C03_SIZE_ID) REFERENCES T02_SIZE(C02_SIZE_ID)
);

-- T08_GALLERY
CREATE TABLE IF NOT EXISTS T08_GALLERY(
	C08_IMAGE_PATH VARCHAR(255) NOT NULL,
    C08_ITEM_ID INT NOT NULL,
    CONSTRAINT FK_T08_T01 FOREIGN KEY (C08_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);
