-- T26_ITEM_GROUP_BACKUP

CREATE TABLE T26_ITEM_GROUP_BACKUP (
	C26_ITEM_GROUP_ID INT NOT NULL,
    C26_ITEM_GROUP_NAME VARCHAR(255) NOT NULL,
    C26_STATUS BIT(1) DEFAULT(1) NOT NULL,
    C26_COPIED_AT DATETIME DEFAULT(current_timestamp())
);

ALTER TABLE T01_ITEM DROP FOREIGN KEY FK_T01_T07;

ALTER TABLE T01_ITEM ADD CONSTRAINT FK_T01_T07 
FOREIGN KEY (C01_ITEM_GROUP_ID) 
REFERENCES T07_ITEM_GROUP(C07_ITEM_GROUP_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE T06_PROVIDER
CHANGE COLUMN C06_PROVIDER_TAX C06_PROVIDER_TAX VARCHAR(10) NOT NULL;

SELECT * FROM T03_ITEM_DETAIL;


-- Xử lý vấn đề của ItemDetail và OrderDetail -- ALTER TABLE T03_ITEM_DETAIL DROP COLUMN C03_ITEM_DETAIL_ID;

-- T03_ITEM_DETAIL
ALTER TABLE T03_ITEM_DETAIL DROP FOREIGN KEY FK_T03_T02; ALTER TABLE T03_ITEM_DETAIL DROP INDEX FK_T03_T02;
ALTER TABLE T03_ITEM_DETAIL DROP FOREIGN KEY FK_T03_T01; ALTER TABLE T03_ITEM_DETAIL DROP INDEX FK_T03_T01;

ALTER TABLE T03_ITEM_DETAIL DROP PRIMARY KEY;
ALTER TABLE T03_ITEM_DETAIL ADD C03_ITEM_DETAIL_ID INT PRIMARY KEY AUTO_INCREMENT FIRST;
ALTER TABLE T03_ITEM_DETAIL ADD CONSTRAINT UNQ_ITEM_SIZE UNIQUE(C03_ITEM_ID,C03_SIZE_ID);

ALTER TABLE T03_ITEM_DETAIL ADD CONSTRAINT FK_T03_T02 FOREIGN KEY (C03_SIZE_ID) REFERENCES T02_SIZE (C02_SIZE_ID);
ALTER TABLE T03_ITEM_DETAIL ADD CONSTRAINT FK_T03_T01 FOREIGN KEY (C03_ITEM_ID) REFERENCES T01_ITEM (C01_ITEM_ID);


-- T12_ORDER_DETAIL
ALTER TABLE T12_ORDER_DETAIL DROP FOREIGN KEY FK_T12_T01; ALTER TABLE T12_ORDER_DETAIL DROP INDEX FK_T12_T01;
ALTER TABLE T12_ORDER_DETAIL DROP FOREIGN KEY FK_T12_T09; ALTER TABLE T12_ORDER_DETAIL DROP INDEX FK_T12_T09;

ALTER TABLE T12_ORDER_DETAIL DROP PRIMARY KEY;
ALTER TABLE T12_ORDER_DETAIL DROP COLUMN C12_ITEM_ID;
ALTER TABLE T12_ORDER_DETAIL ADD C12_ITEM_DETAIL_ID INT NOT NULL AFTER C12_ORDER_ID;

ALTER TABLE T12_ORDER_DETAIL ADD PRIMARY KEY (C12_ORDER_ID, C12_ITEM_DETAIL_ID);
ALTER TABLE T12_ORDER_DETAIL ADD CONSTRAINT FK_T12_T03 FOREIGN KEY(C12_ITEM_DETAIL_ID) REFERENCES T03_ITEM_DETAIL(C03_ITEM_DETAIL_ID);
ALTER TABLE T12_ORDER_DETAIL ADD CONSTRAINT FK_T12_T09 FOREIGN KEY(C12_ORDER_ID) REFERENCES T09_ORDER(C09_ORDER_ID);

