-- T07_ITEM_GROUP_BACKUP

CREATE TABLE T26_ITEM_GROUP_BACKUP(
	C26_ITEM_GROUP_ID INT NOT NULL,
    C26_ITEM_GROUP_NAME VARCHAR(255) NOT NULL,
    C26_STATUS BIT(1) DEFAULT (1) NOT NULL,
    C26_COPIED_AT DATETIME DEFAULT (current_timestamp())
);