
-- T15_CUSTOMER
-- T11_PAYMENT_METHOD
-- T18_DELIVERY_ADDRESS

-- T15_CUSTOMER
CREATE TABLE IF NOT EXISTS T15_CUSTOMER(
	C15_CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    C15_CUSTOMER_NAME VARCHAR(255) NOT NULL,
    C15_CUSTOMER_EMAIL TEXT NOT NULL,
    C15_CUSTOMER_ADDRESS TEXT NOT NULL,
    C15_CUSTOMER_PHONE VARCHAR(20) NOT NULL,
    C15_CUSTOMER_PASSWORD TEXT NOT NULL,
    C15_GMAIL_TOKEN TEXT NOT NULL 
);

-- T11_PAYMENT_METHOD
CREATE TABLE IF NOT EXISTS T11_PAYMENT_METHOD(
	C11_PAYMENT_METHOD_ID INT PRIMARY KEY AUTO_INCREMENT,
    C11_PAYMENT_METHOD_NAME VARCHAR(255) NOT NULL
);
-- T18_DELIVERY_ADDRESS
CREATE TABLE IF NOT EXISTS T18_DELIVERY_ADDRESS(
	C18_DELIVERY_ADDRESS_ID INT PRIMARY KEY AUTO_INCREMENT,
    C18_CUSTOMER_ID INT NOT NULL,
    C18_RECEIVER_NAME VARCHAR(255) NOT NULL,
    C18_RECEIVER_PHONE VARCHAR(20) NOT NULL,
    C18_ADDRESS TEXT NOT NULL,
    CONSTRAINT FK_T18_T15 FOREIGN KEY (C18_CUSTOMER_ID) REFERENCES T15_CUSTOMER(C15_CUSTOMER_ID)
);

