-- T26_ITEM_GROUP_BACKUP

CREATE TABLE T26_ITEM_GROUP_BACKUP (
	C26_ITEM_GROUP_ID INT NOT NULL,
    C26_ITEM_GROUP_NAME VARCHAR(255) NOT NULL,
    C26_STATUS BIT(1) DEFAULT(1) NOT NULL,
    C26_COPIED_AT DATETIME DEFAULT(current_timestamp())
);

ALTER TABLE T01_ITEM
DROP FOREIGN KEY FK_T01_T07;

ALTER TABLE T01_ITEM ADD CONSTRAINT FK_T01_T07 
FOREIGN KEY (C01_ITEM_GROUP_ID) 
REFERENCES T07_ITEM_GROUP(C07_ITEM_GROUP_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE `java24_shopping`.`t06_provider` 
CHANGE COLUMN `C06_PROVIDER_TAX` `C06_PROVIDER_TAX` VARCHAR(10) NOT NULL ;

