-- T22_TAX
CREATE TABLE IF NOT EXISTS T22_TAX(
	C22_TAX_ID INT PRIMARY KEY AUTO_INCREMENT,
	C22_TAX_IN_PERCENT INT NOT NULL,
	C22_TOTAL_OF_MONEY FLOAT(10,2),
	C22_DATE_SUBMIT DATETIME,
	C22_DATE_FROM DATE NOT NULL,
	C22_DATE_UNTIL DATE NOT NULL,
	C22_TAX_PAYER_ID INT NOT NULL,
    CONSTRAINT FK_T22_T16 FOREIGN KEY (C22_TAX_PAYER_ID) REFERENCES T16_EMPLOYEE(C16_EMPLOYEE_ID)
);
-- T23_CART
CREATE TABLE IF NOT EXISTS T23_CART(
	C23_CART_ID INT PRIMARY KEY AUTO_INCREMENT,
	C23_CUSTOMER_ID INT NOT NULL,
	C23_DATE_CREATED DATETIME NOT NULL DEFAULT(current_timestamp()),
	CONSTRAINT FK_T23_T16 FOREIGN KEY (C23_CUSTOMER_ID) REFERENCES T16_EMPLOYEE(C16_EMPLOYEE_ID)
);


-- T24_SHOPPING_CART 
CREATE TABLE IF NOT EXISTS T24_SHOPPING_CART(
	C24_CART_ID INT,
	C24_ITEM_ID INT,
	C24_AMOUNT INT NOT NULL,
	C24_DATE_ADDING DATETIME NOT NULL,
	C24_DATE_REMOVING DATETIME NOT NULL,
    PRIMARY KEY (C24_CART_ID,C24_ITEM_ID),
    CONSTRAINT FK_T24_T23 FOREIGN KEY (C24_CART_ID) REFERENCES T23_CART(C23_CART_ID),
    CONSTRAINT FK_T24_T01 FOREIGN KEY (C24_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);


-- T25_CART_LATER_ON
CREATE TABLE IF NOT EXISTS T25_CART_LATER_ON(
	C25_CUSTOMER_ID INT NOT NULL,
	C25_ITEM_ID INT NOT NULL,
	C25_AMOUNT INT NOT NULL,
    PRIMARY KEY (C25_CUSTOMER_ID, C25_ITEM_ID),
     CONSTRAINT FK_T25_T15 FOREIGN KEY (C25_CUSTOMER_ID) REFERENCES T15_CUSTOMER(C15_CUSTOMER_ID),
    CONSTRAINT FK_T25_T01 FOREIGN KEY (C25_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);


