-- T13_ORDER_STATUS
CREATE TABLE IF NOT EXISTS T13_ORDER_STATUS (
	C13_ORDER_STATUS_ID INT PRIMARY KEY AUTO_INCREMENT,
	C13_ORDER_STATUS_DESC VARCHAR(255) NOT NULL
);

-- T14_ORDER_STATUS_DETAIL
CREATE TABLE IF NOT EXISTS T14_ORDER_STATUS_DETAIL (
	C14_ORDER_ID INT NOT NULL,
	C14_ORDER_STATUS_ID INT NOT NULL,
	C14_EMPLOYEE_ID INT NOT NULL, 
	C14_LAST_UPDATED DATETIME DEFAULT(current_timestamp()),
    PRIMARY KEY (C14_ORDER_ID, C14_ORDER_STATUS_ID),
    CONSTRAINT FK_T14_T09 FOREIGN KEY (C14_ORDER_ID) REFERENCES T09_ORDER(C09_ORDER_ID),
    CONSTRAINT FK_T14_T13 FOREIGN KEY (C14_ORDER_STATUS_ID) REFERENCES T13_ORDER_STATUS(C13_ORDER_STATUS_ID),
    CONSTRAINT FK_T14_T16 FOREIGN KEY (C14_EMPLOYEE_ID) REFERENCES T16_EMPLOYEE(C16_EMPLOYEE_ID)
);

-- T20_ROLE
CREATE TABLE IF NOT EXISTS T20_ROLE (
	C20_ROLE_ID INT PRIMARY KEY AUTO_INCREMENT,
	C20_ROLE_NAME VARCHAR(255) NOT NULL
);


-- T21_ROLE_DETAIL
CREATE TABLE IF NOT EXISTS T21_ROLE_DETAIL (
	C21_EMPLOYEE_ID INT,
	C21_ROLE_ID INT,
    PRIMARY KEY (C21_EMPLOYEE_ID, C21_ROLE_ID),
    CONSTRAINT FK_T21_T16 FOREIGN KEY (C21_EMPLOYEE_ID) REFERENCES T16_EMPLOYEE(C16_EMPLOYEE_ID),
    CONSTRAINT FK_T21_T20 FOREIGN KEY (C21_ROLE_ID) REFERENCES T20_ROLE(C20_ROLE_ID)
);
