-- Xóa cơ sở dữ liệu
DROP DATABASE IF EXISTS company;

-- Tạo cơ sử dữ liệu
CREATE DATABASE IF NOT EXISTS company CHAR SET utf8mb4;

USE company;


CREATE TABLE IF NOT EXISTS T01_DEPARTMENT(
	C01_DEPARTMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
	C01_DEPARTMENT_NAME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS T02_EMPLOYEE(
	C02_EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
	C02_EMPLOYEE_NAME VARCHAR(255) UNIQUE NOT NULL,
    C02_ADDRESS VARCHAR(255) NOT NULL,
    C02_GENDER BIT(1) NOT NULL,
    C02_SALARY DECIMAL(15,2) NOT NULL,
    C02_DATE_OF_BIRTH DATE NOT NULL,
    C02_DATE_HIRED DATE NOT NULL,
    C02_DEPARTMENT_ID INT NOT NULL,
    C02_SUPERVISOR_ID INT,
    CONSTRAINT FK_T02_T01 FOREIGN KEY (C02_DEPARTMENT_ID) REFERENCES T01_DEPARTMENT(C01_DEPARTMENT_ID),
    CONSTRAINT FK_T02_T02 FOREIGN KEY (C02_SUPERVISOR_ID) REFERENCES T02_EMPLOYEE(C02_EMPLOYEE_ID)
);

CREATE TABLE IF NOT EXISTS T03_PROJECT (
    C03_PROJECT_ID INT AUTO_INCREMENT PRIMARY KEY,
    C03_PROJECT_NAME VARCHAR(250) NOT NULL UNIQUE,
    C03_START_DATE DATE NOT NULL,
    C03_END_DATE DATE NOT NULL,
    C03_REVENUE DECIMAL(15,2) NOT NULL,  
    C03_PROJECT_MANAGER_ID INT,      
    CONSTRAINT FK_T03_T02 FOREIGN KEY (C03_PROJECT_MANAGER_ID) REFERENCES T02_EMPLOYEE(C02_EMPLOYEE_ID)
);

CREATE TABLE IF NOT EXISTS T04_EMPLOYEE_PROJECT (
    C04_PROJECT_ID INT NOT NULL,
    C04_EMPLOYEE_ID INT NOT NULL,
    C04_WORK_HOURS DECIMAL(10,2),
	PRIMARY KEY (C04_PROJECT_ID, C04_EMPLOYEE_ID),
    CONSTRAINT FK_T04_T03
        FOREIGN KEY (C04_PROJECT_ID)
        REFERENCES T03_PROJECT(C03_PROJECT_ID),

    CONSTRAINT FK_T04_T02
        FOREIGN KEY (C04_EMPLOYEE_ID)
        REFERENCES T02_EMPLOYEE(C02_EMPLOYEE_ID)
);


CREATE TABLE IF NOT EXISTS T05_DEPARTMENT_MANAGER (
    C05_DEPARTMENT_MANAGER_ID INT PRIMARY KEY AUTO_INCREMENT,
    C05_DEPARTMENT_ID INT NOT NULL,
    C05_EMPLOYEE_ID INT NOT NULL,
    C05_START_DATE DATE NOT NULL,

    CONSTRAINT FK_T05_T01
        FOREIGN KEY (C05_DEPARTMENT_ID)
        REFERENCES T01_DEPARTMENT(C01_DEPARTMENT_ID),

    CONSTRAINT FK_T05_T02
        FOREIGN KEY (C05_EMPLOYEE_ID)
        REFERENCES T02_EMPLOYEE(C02_EMPLOYEE_ID)
);



